spring:
  application:
     name: apigateway-sample

# Logging
##https://docs.spring.io/spring-boot/docs/2.4.2/reference/html/spring-boot-features.html#boot-features-logging  
logging:
  level:
    ROOT: INFO
    web: INFO
    io.opentelemetry: DEBUG

  pattern:
    - console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name},%X{trace_id},%X{span_id}] ${PID:- } --- [%15.15t] %-40.40logger{39} : %m %n%wEx"
